import {ITEMS,TEAMS,ENEMIES,CHARACTERS,SCENES,BARKS,CHAPTERS,WAVE_NAMES,WAVE_COUNT,TICK,chapter,wavePreview} from './content.js';
import {createGame,makeTower,sets,modifiers,place,canPlace,stash,discard,resume,step,acceptReward,reroll,clone,serialize,deserialize,restoreCheckpoint,cells} from './sim.js';
import {BoardRenderer,portrait,itemIcon} from './render.js';
const root=document.querySelector('#app'),SAVE='last-rig-save-v1',JOURNAL='last-rig-journal-v1';
let lastSound=0,lastDraw=0,invPage=0,helpPage=0,journalPage=0,radioTimer=null;
let state=null,renderer=null,screen='home',selected=null,ghost=null,paused=false,speed=1,modalOpen=false,last=0,acc=0,uiClock=0,history=[],currentScene=null,sceneIndex=0,storyAfter=null,choiceType=null,muted=true,audio=null,toastTimer=null,lastBark=-100,journal=[];
try{journal=JSON.parse(localStorage.getItem(JOURNAL)||'[]');}catch{}
const $=s=>document.querySelector(s),fmt=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2600);}
function save(){if(!state)return;try{localStorage.setItem(SAVE,serialize(state));localStorage.setItem(JOURNAL,JSON.stringify(journal.slice(-70)));}catch{toast('이 브라우저에서는 저장할 수 없어요. 현재 여행은 계속할 수 있어요.');}}
function saved(){try{return localStorage.getItem(SAVE);}catch{return null;}}
function remember(who,text){journal.push({who,text});journal=journal.slice(-70);}
function sound(type){if(muted||performance.now()-lastSound<85)return;lastSound=performance.now();try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type==='coil'?'sine':type==='mortar'?'triangle':'square';o.frequency.setValueAtTime(({nail:260,saw:90,harpoon:160,mortar:65,flame:100,winch:340,coil:580})[type]||320,audio.currentTime);o.frequency.exponentialRampToValueAtTime(40,audio.currentTime+.09);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.11);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.12);}catch{}}
function home(){screen='home';modalOpen=false;root.innerHTML=`<main class="home"><header class="home-nav"><div class="brand"><span class="brand-mark">⚙</span> THE LAST RIG</div><small>A GOBLIN GETAWAY</small></header><section class="hero"><div><div class="eyebrow">고철 조립 디펜스 · 약 30분의 탈출</div><h1>고블린은<br><span>퇴각 중.</span></h1><p class="lede">버려진 고철로,<br>버릴 수 없는 사람들을 지켜라.</p><p class="lede">못총을 얹고, 톱을 맞물리고, 추격대를 따돌려라.<br>엉망인 이 요새가 우리의 마지막 집이다.</p><div class="hero-actions"><button id="new-game" class="primary">요새에 탑승하기 ↗</button>${saved()?'<button id="continue-game">여행 이어가기</button>':''}<button id="home-help" class="quiet">정비사 안내서</button></div><div class="hero-note">마우스 또는 터치로 조립 · 정비 중 시간 정지 · 자동 저장</div></div><div class="poster"><div class="poster-stamp">전원 탑승. 아무도 두고 가지 않는다.</div><canvas id="home-board" aria-label="고철 무기를 조립한 고블린 요새"></canvas><div class="poster-label"><span>RIG NO. 027 / BUILT FROM SCRAP</span><span>출구는 앞으로.</span></div></div></section><section class="crew-preview">${Object.entries(CHARACTERS).map(([key,c])=>`<div class="crew-mini"><canvas data-portrait="${key}"></canvas><div><b>${c.name} <small> / ${c.job}</small></b><p>${c.tag}</p></div></div>`).join('')}</section><footer class="home-foot"><span>작은 발명들이 모여, 하나의 집이 된다.</span><span>HAND-BUILT IN JAVASCRIPT</span></footer></main>`;
document.querySelectorAll('[data-portrait]').forEach(c=>portrait(c,c.dataset.portrait));const demo=createGame();demo.wave=8;demo.towers.push(makeTower(demo,'mortar',6,5),makeTower(demo,'coil',6,2),makeTower(demo,'winch',2,2),makeTower(demo,'feeder',4,3,1),makeTower(demo,'flame',9,5),makeTower(demo,'battery',5,5));renderer=new BoardRenderer($('#home-board'));renderer.draw(demo,null,null,0);$('#new-game').onclick=()=>{if(saved())confirmNew();else startNew();};if($('#continue-game'))$('#continue-game').onclick=()=>{try{state=deserialize(saved());paused=true;gameUI();if(state.phase==='victory')ending();else if(state.phase==='defeat')defeat();else if(state.pendingScene)showScene(state.pendingScene);else if(state.phase==='reward')rewardModal();else toast('저장한 여행을 불러왔어요. 준비되면 계속하세요.');}catch{toast('저장 파일을 읽을 수 없어요. 새 여행을 시작해 주세요.');}};$('#home-help').onclick=help;}
function confirmNew(){showModal(`<div class="eyebrow">새로운 출발</div><h2>처음부터 다시 달릴까요?</h2><p>현재 저장된 여행은 새 여행으로 바뀝니다. 동료들의 대사 기록은 남아요.</p><div class="modal-actions"><button id="cancel-new">돌아가기</button><button id="yes-new" class="primary">새 여행 시작</button></div>`);$('#cancel-new').onclick=closeModal;$('#yes-new').onclick=()=>{closeModal();startNew();};}
function startNew(){state=createGame((Date.now()&0xffffffff)>>>0);paused=false;selected=null;ghost=null;history=[];gameUI();showScene('intro');save();}
function gameUI(){
 screen='game';root.innerHTML=`<main class="game"><canvas id="board" aria-label="고철 요새 전장. 기물을 선택하고 빈 갑판을 눌러 배치합니다."></canvas>
 <header class="hud"><div class="mission"><small id="chapter-label"></small><h2 id="wave-title"></h2><span id="wave-number"></span><span id="phase-label"></span></div><div class="engine"><label>엔진</label><strong id="hp"></strong><div class="hp-track"><i id="hp-fill"></i></div></div><div class="run-stats"><strong id="kills"></strong><span id="time"></span></div><button id="game-options" aria-label="게임 메뉴">☰</button></header>
 <div class="route"><span id="distance-label"></span><div class="progress-track"><div id="journey-fill"></div></div></div>
 <nav class="field-tabs"><button id="intel">추격대</button><button id="combos">조합 <span id="links-count"></span></button><button id="journal">통신 기록</button></nav>
 <div class="radio"><canvas id="radio-portrait"></canvas><div><b id="radio-name"></b><p id="radio-text"></p></div></div>
 <div class="pause-banner hidden" id="pause-banner"><b>잠깐 숨 고르기</b><button class="primary" id="unpause">추격전 계속</button></div>
 <footer class="command-deck"><div class="deck-heading"><span id="reward-progress"></span><span class="play-controls"><button id="pause">일시정지</button><button id="speed">×1</button></span></div><div id="workshop"></div></footer></main>`;
 renderer=new BoardRenderer($('#board'));$('#board').addEventListener('pointerdown',boardTap);$('#game-options').onclick=optionsMenu;$('#intel').onclick=()=>intelModal();$('#combos').onclick=()=>comboModal();$('#journal').onclick=showJournal;$('#pause').onclick=togglePause;$('#unpause').onclick=togglePause;$('#speed').onclick=()=>{speed=speed===1?2:1;$('#speed').textContent=`×${speed}`;};setRadio('rivet','정비사, 난 엔진을 볼게. 갑판의 못총과 톱은 네가 맡아 줘.',false);refresh();
}
function optionsMenu(){showModal(`<div class="eyebrow">잠시 정차</div><h2>운전석</h2><div class="menu-grid"><button id="sound">${muted?'소리 켜기':'소리 끄기'}</button><button id="help">정비사 안내서</button><button id="fullscreen">화면 크게 보기</button><button id="menu">저장하고 제목으로</button></div><div class="modal-actions"><button id="close-options" class="primary">전장으로</button></div>`);$('#sound').onclick=()=>{muted=!muted;if(!muted)sound('winch');optionsMenu();};$('#help').onclick=help;$('#menu').onclick=()=>{paused=true;save();closeModal();home();};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('현재 브라우저에서는 주소창을 접으면 더 넓게 볼 수 있어요.'));};$('#close-options').onclick=closeModal;}
function intelModal(index=0){const types=wavePreview(state.wave),key=types[index],e=ENEMIES[key];showModal(`<div class="eyebrow">추격 ${Math.min(18,state.wave+1)} / 18</div><h2>${WAVE_NAMES[Math.min(state.wave,17)]}</h2><div class="tabs">${types.map((k,i)=>`<button data-enemy-page="${i}" class="${index===i?'primary':''}">${({grunt:'보병',swarm:'인형병',runner:'정찰병',armor:'중장갑',ranger:'사수',captain:'지휘관',boss:'지휘차',raider:'강습병'})[k]}</button>`).join('')}</div><div class="combo-detail"><h3>${e.name}</h3><p class="page-copy">${({raider:'방패를 들고 빠르게 달립니다. 기본 무기만으로 놓칠 수 있습니다. 추가 화력을 겹치거나 속박으로 시간을 벌어주세요.',grunt:'방패를 앞세운 보병입니다. 점사와 근접으로 빈틈을 메워주세요.',swarm:'한꺼번에 올라탑니다. 여러 적을 함께 베는 톱과 폭발이 효과적입니다.',runner:'좁은 틈으로 달립니다. 출구 사거리와 감속을 확인해주세요.',armor:'판금 갑옷은 약한 탄을 막습니다. 작살의 관통과 화상이 효과적입니다.',ranger:'거리를 벌리고 움직입니다. 한 곳에만 화력을 몰지 마세요.',captain:'주변 추격대를 재촉합니다. 오래 머물게 두지 마세요.',boss:'엔진에 도달하면 패배합니다. 전 구간의 화력을 겹치고, 속박으로 시간을 벌어주세요.'})[key]}</p></div><div class="modal-actions"><button id="intel-close" class="primary">확인</button></div>`);document.querySelectorAll('[data-enemy-page]').forEach(b=>b.onclick=()=>intelModal(Number(b.dataset.enemyPage)));$('#intel-close').onclick=closeModal;}
function comboModal(key='iron'){const ss=sets(state),t=TEAMS[key];showModal(`<div class="eyebrow">서로 맞물리는 고철</div><h2>작업반 조합</h2><div class="tabs">${Object.entries(TEAMS).map(([k,v])=>`<button data-team="${k}" class="${key===k?'primary':''}">${v.name} ${ss[k]}</button>`).join('')}</div><div class="combo-detail"><h3>${t.name} · 서로 다른 ${ss[key]}종</h3><p class="${ss[key]>=2?'unlocked':''}">2종 — ${t.two}</p><p class="${ss[key]>=3?'unlocked':''}">3종 — ${t.three}</p><small>같은 기물을 여러 개 놓아도 한 종류로 셉니다. 지원 장치는 변이 닿아야 연결됩니다.</small></div><div class="modal-actions"><button id="combo-close" class="primary">전장으로</button></div>`);document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>comboModal(b.dataset.team));$('#combo-close').onclick=closeModal;}
function togglePause(){if(state.phase!=='combat'){toast('정비 중에는 시간이 흐르지 않아요.');return;}paused=!paused;refreshStats();}
function pushHistory(){history.push(clone(state.towers));if(history.length>20)history.shift();}
function refresh(){if(screen!=='game')return;refreshStats();refreshWorkshop();const links=state.towers.filter(t=>t.x!==null).reduce((n,t)=>n+modifiers(state,t).links.length,0);$('#links-count').textContent=links;}
function refreshStats(){if(screen!=='game')return;$('#chapter-label').textContent=`${chapter(state.wave)+1}막 · ${CHAPTERS[chapter(state.wave)]}`;$('#wave-title').textContent=WAVE_NAMES[Math.min(state.wave,17)];$('#wave-number').textContent=`${Math.min(18,state.wave+1)} / 18`;$('#phase-label').textContent=({garage:'정비 중 · 시간 정지',combat:paused?'일시정지':'추격전',reward:'새 고철 발견',victory:'전원 도착',defeat:'엔진 정지'})[state.phase];$('#hp').innerHTML=`${Math.ceil(state.hp)} <em>/ ${state.maxHp}</em>`;$('#hp-fill').style.width=`${state.hp/state.maxHp*100}%`;$('#hp-fill').style.background=state.hp<30?'#e78c70':'#a9cc98';$('#kills').innerHTML=`${state.kills} <em>격퇴</em>`;$('#time').textContent=fmt(state.time);const progress=Math.min(1,(state.wave+Math.min(.95,state.waveTime/95))/18);$('#journey-fill').style.width=`${progress*100}%`;$('#distance-label').textContent=`${Math.max(0,Math.ceil((1-progress)*27))} km 남음`;$('#reward-progress').textContent=state.rewards>=18?'요새 조립 완료':`다음 고철까지 ${Math.max(0,state.rewardAt-state.kills)} 처치`;$('#pause-banner').classList.toggle('hidden',!paused||state.phase!=='combat'||modalOpen);$('#pause').textContent=paused?'계속':'일시정지';$('.game').dataset.phase=state.phase;}
function refreshWorkshop(){
 const el=$('#workshop');if(!['garage','reward'].includes(state.phase)){el.innerHTML=`<div class="combat-note">${state.phase==='combat'?'무기를 누르면 사거리와 전투 기록을 볼 수 있습니다.':''}</div>`;return;}
 const t=state.towers.find(a=>a.id===selected),d=t?ITEMS[t.type]:null,bench=state.towers.filter(a=>a.x===null).length,valid=ghost&&canPlace(state,ghost.type,ghost.x,ghost.y,ghost.r,ghost.id),size=innerWidth<720?3:6,pages=Math.max(1,Math.ceil(state.towers.length/size));invPage=Math.min(invPage,pages-1);
 el.innerHTML=`<div class="workshop"><div class="item-status">${t?`<b>${d.name} ${'★'.repeat(t.level)}</b><span>${ghost?(valid?'설치 가능':'막힌 자리'):d.role}</span><button id="info-item" aria-label="기물 설명">?</button>`:'<b>갑판을 다시 맞춰 보자.</b><span>기물 → 빈 칸 → 설치 확인</span>'}</div>
 <div class="inventory-row"><button id="inv-prev" aria-label="이전 기물" ${invPage===0?'disabled':''}>‹</button><div class="inventory">${state.towers.slice(invPage*size,(invPage+1)*size).map(a=>`<button data-item="${a.id}" class="${selected===a.id?'selected':''}" aria-label="${ITEMS[a.type].name} 선택"><canvas data-item-icon="${a.type}"></canvas><span>${ITEMS[a.type].name}${a.x===null?' ◇':''}</span></button>`).join('')}</div><button id="inv-next" aria-label="다음 기물" ${invPage===pages-1?'disabled':''}>›</button><small>${invPage+1}/${pages}</small></div>
 <div class="actionbar">${t?'<button id="rotate">↻ 회전</button><button id="stash">보관</button><button id="discard">폐기</button><button id="cancel-select">취소</button>':`${state.pendingPick?'<button id="repick">다시 선택</button>':''}<button id="undo" ${history.length?'':'disabled'}>되돌리기</button>`}${ghost?`<button id="confirm-place" class="primary" ${valid?'':'disabled'}>설치 확인</button>`:`<button id="resume" class="primary" ${bench>1?'disabled':''}>${state.resumeMidWave?'전투 계속':'출발'}</button>`}</div></div>`;
 document.querySelectorAll('[data-item-icon]').forEach(c=>itemIcon(c,c.dataset.itemIcon));document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.item);ghost=null;refreshWorkshop();});$('#inv-prev').onclick=()=>{invPage--;refreshWorkshop();};$('#inv-next').onclick=()=>{invPage++;refreshWorkshop();};
 if($('#repick'))$('#repick').onclick=()=>{state=deserialize(state.pendingPick);selected=null;ghost=null;history=[];refresh();save();rewardModal();};if($('#undo'))$('#undo').onclick=()=>{if(history.length){state.towers=history.pop();selected=null;ghost=null;refresh();save();}};
 if(t){$('#info-item').onclick=()=>{showModal(`<div class="eyebrow">${TEAMS[d.team].name} / ${d.role}</div><h2>${d.name} ${'★'.repeat(t.level)}</h2><p>${d.desc}</p><p>누적 유효 피해 ${Math.round(t.damage)} · 격퇴 ${t.kills}</p><div class="modal-actions"><button id="item-close" class="primary">조립 계속</button></div>`);$('#item-close').onclick=closeModal;};$('#rotate').onclick=()=>{if(ghost)ghost.r=(ghost.r+1)%4;else ghost={...t,x:t.x??3,y:t.y??2,r:(t.r+1)%4};refreshWorkshop();};$('#stash').onclick=()=>{pushHistory();stash(state,t.id);ghost=null;selected=null;refresh();save();};$('#discard').onclick=()=>confirmDiscard(t);$('#cancel-select').onclick=()=>{selected=null;ghost=null;refreshWorkshop();};}
 if(ghost)$('#confirm-place').onclick=()=>{pushHistory();if(place(state,ghost.id,ghost.x,ghost.y,ghost.r)){ghost=null;refresh();save();sound('winch');}};else $('#resume').onclick=launch;
}
function boardTap(ev){if(modalOpen)return;ev.preventDefault();const p=renderer.point(ev.clientX,ev.clientY),t=state.towers.find(a=>a.x!==null&&cells(a).some(([x,y])=>x===p.x&&y===p.y));if(!['garage','reward'].includes(state.phase)){selected=t?.id??null;if(t)toast(`${ITEMS[t.type].name} · 유효 피해 ${Math.round(t.damage)} · 격퇴 ${t.kills}`);return;}if(selected!==null){const item=state.towers.find(a=>a.id===selected);if(item)ghost={...item,...p,r:ghost?.r??item.r};}else if(t)selected=t.id;else toast('먼저 갑판의 기물이나 아래 목록에서 하나를 선택하세요.');refreshWorkshop();}
function confirmDiscard(t){showModal(`<div class="eyebrow">갑판 비우기</div><h2>${ITEMS[t.type].name}을 폐기할까요?</h2><p>기물은 사라지지만 정비 중 ‘되돌리기’로 복원할 수 있어요.</p><div class="modal-actions"><button id="keep-item">남겨두기</button><button id="scrap-item" class="primary">폐기하기</button></div>`);$('#keep-item').onclick=closeModal;$('#scrap-item').onclick=()=>{pushHistory();discard(state,t.id);selected=null;ghost=null;closeModal();refresh();save();};}
function launch(){const links=state.towers.filter(t=>t.x!==null).some(t=>modifiers(state,t).links.length);if(links&&!state.seen.includes('firstCombo')){showScene('firstCombo',launch);return;}selected=null;ghost=null;history=[];paused=false;if(resume(state)){delete state.pendingPick;save();refresh();}else toast('설치하지 않은 기물은 하나만 보관할 수 있어요. 나머지는 배치하거나 폐기해 주세요.');}
function characterPortrait(canvas,who){portrait(canvas,who,150,{badge:!state?.seen.includes('chapter1')&&!(currentScene==='chapter1'&&sceneIndex>=7)});}
function setRadio(who,text,record=true){if(!$('#radio-name'))return;characterPortrait($('#radio-portrait'),who);$('#radio-name').textContent=`${CHARACTERS[who].name} / ${CHARACTERS[who].job}`;$('#radio-text').textContent=text;clearTimeout(radioTimer);$('.radio')?.classList.toggle('speaking',record);if(record){remember(who,text);radioTimer=setTimeout(()=>$('.radio')?.classList.remove('speaking'),6500);}}
function bark(kind){if(state.time-lastBark<40)return;const choices=BARKS[kind],line=choices[Math.floor(state.kills/7)%choices.length];setRadio(...line);lastBark=state.time;}
function showModal(html,cls=''){document.querySelector('.modal-backdrop')?.remove();modalOpen=true;const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<section class="modal ${cls}" role="dialog" aria-modal="true" tabindex="-1">${html}</section>`;document.body.appendChild(el);el.querySelector('.modal').focus();refreshStats();}
function closeModal(){document.querySelector('.modal-backdrop')?.remove();modalOpen=false;currentScene=null;refreshStats();}
function showScene(key,after=null){if(state.seen.includes(key)){after?.();return;}currentScene=key;sceneIndex=0;storyAfter=after;state.pendingScene=key;save();drawScene();}
function drawScene(){
 const scene=SCENES[currentScene],key=currentScene,[who,text,acting='']=scene.lines[sceneIndex],ch=CHARACTERS[who];
 const context=Object.entries(scene.beats||{}).filter(([index])=>Number(index)<=sceneIndex).at(-1)?.[1]??scene.context;
 showModal(`<header class="story-heading"><div class="eyebrow">CABIN RADIO / ${scene.title}</div><p class="story-context">${escape(context)}</p></header><div class="story-line"><canvas id="story-portrait"></canvas><div class="story-copy"><div class="story-speaker"><b>${ch.name}</b><small>${ch.job}</small></div><p class="acting">${escape(acting)}</p><blockquote>“${escape(text)}”</blockquote></div></div><footer class="story-footer"><div class="story-steps" aria-label="${sceneIndex+1} / ${scene.lines.length}">${scene.lines.map((_,i)=>`<i class="${i<=sceneIndex?'on':''}"></i>`).join('')}</div><div class="modal-actions"><button id="story-next" class="primary">${sceneIndex===scene.lines.length-1?'대화 마침 →':'다음 →'}</button></div></footer>`,'story-modal');
 characterPortrait($('#story-portrait'),who);
 $('#story-next').onclick=()=>{remember(who,text);setRadio(who,text,false);sceneIndex++;if(sceneIndex<scene.lines.length){currentScene=key;drawScene();}else{state.seen.push(key);delete state.pendingScene;const after=storyAfter;closeModal();save();after?.();}};
}
function footprint(type){const a=ITEMS[type].shape,w=Math.max(...a.map(p=>p[0]))+1,h=Math.max(...a.map(p=>p[1]))+1;return '<span class="footprint" aria-label="'+a.length+'칸 모양" style="grid-template-columns:repeat('+w+',8px)">'+Array.from({length:w*h},(_,i)=>'<i class="'+(a.some(([x,y])=>x===i%w&&y===Math.floor(i/w))?'filled':'')+'"></i>').join('')+'</span>';}
function rewardModal(){choiceType=state.choices[0];drawReward();}
function drawReward(){const d=ITEMS[choiceType],up=state.towers.find(t=>t.type===choiceType&&t.level<3);showModal(`<div class="eyebrow">회수한 고철 / ${state.rewards+1}번째 선택</div><h2>이번엔 뭘 만들어 볼까?</h2><div class="choice-tabs">${state.choices.map(k=>`<button data-choice="${k}" class="${choiceType===k?'primary':''}">${ITEMS[k].name}</button>`).join('')}</div><div class="choice-detail"><canvas data-choice-icon="${choiceType}"></canvas><div><small>${TEAMS[d.team].name} · ${d.role}</small><h3>${d.name} ${footprint(choiceType)}</h3><p>${d.desc}</p>${up?`<span class="upgrade">기존 ★${up.level} 기물을 ★${up.level+1}로 강화할 수도 있습니다.</span>`:`<small>${d.shape.length}칸 · ${d.directional?'회전 방향으로 발사':'자동 조준'}</small>`}</div></div><div class="modal-actions"><button id="reroll" ${state.rerolls?'':'disabled'}>다른 고철 ${state.rerolls}</button><button id="repair">수리 +16</button>${up?'<button id="upgrade">기존 강화</button>':''}<button id="take" class="primary">가져와 조립</button></div>`);itemIcon(document.querySelector('[data-choice-icon]'),choiceType);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choiceType=b.dataset.choice;drawReward();});$('#reroll').onclick=()=>{if(reroll(state)){choiceType=state.choices[0];save();drawReward();}};$('#repair').onclick=()=>takeReward('repair');$('#take').onclick=()=>takeReward(choiceType);if(up)$('#upgrade').onclick=()=>takeReward(choiceType,'upgrade');}
function takeReward(type,mode){const before=serialize(state);const t=acceptReward(state,type,mode);state.pendingPick=before;selected=null;ghost=null;history=[];closeModal();invPage=Math.floor(Math.max(0,state.towers.length-1)/(innerWidth<720?3:6));refresh();save();if(t)toast(mode==='upgrade'?`${ITEMS[type].name} 강화 완료. 성능이 높아졌어요.`:'새 기물을 선택했어요. 빈 칸을 누르고 설치 확인하세요.');}
const HELP=[['갑판에 무기 설치','기물을 누르고 빈 칸을 누른 뒤 설치 확인. 회전 버튼으로 방향을 바꿉니다. 갈색 통로에는 설치할 수 없습니다.'],['공간이 부족하면','보관으로 잠시 치우고 재배치하세요. 정비 중에는 시간이 멈춥니다. 예비 기물은 한 개까지 가지고 출발할 수 있습니다. 폐기는 되돌릴 수 있습니다.'],['변이 닿으면 연결','급탄기와 못총, 냉각기와 박격포, 축전기와 코일. 연결된 호스가 밝아지는지 확인하세요. 같은 지원은 중복되지 않습니다.'],['작업반과 성장','다른 종류의 같은 작업반 기물 2종·3종을 설치하면 세트 효과가 생깁니다. 처치 보상은 새 기물, 기존 기물 강화, 수리 중에서 선택합니다.'],['다가올 적에 맞춰','몰려오는 적은 톱·관통·폭발로, 빠른 적은 감속·속박으로, 장갑은 작살과 화상으로 대응하세요. 추격대 버튼에서 다음 공격을 확인할 수 있습니다.'],['실패해도 다시','구간 시작 지점에서 재시도할 수 있습니다. 저장은 자동이며 브라우저를 벗어나면 일시정지합니다. 전투 22~25분과 정비·대화로 이루어진 탈출입니다.']];
function help(){helpPage=0;drawHelp();}
function drawHelp(){const [title,text]=HELP[helpPage];showModal(`<div class="eyebrow">정비사 안내서 ${helpPage+1} / ${HELP.length}</div><h2>${title}</h2><p class="page-copy">${text}</p><div class="modal-actions"><button id="help-prev" ${helpPage===0?'disabled':''}>이전</button><button id="close-help">닫기</button><button id="help-next" class="primary">${helpPage===HELP.length-1?'알겠어':'다음'}</button></div>`);$('#help-prev').onclick=()=>{helpPage--;drawHelp();};$('#help-next').onclick=()=>{if(helpPage===HELP.length-1)closeModal();else{helpPage++;drawHelp();}};$('#close-help').onclick=closeModal;}
function showJournal(){journalPage=Math.max(0,journal.length-1);drawJournal();}
function drawJournal(){const a=journal[journalPage];showModal(`<div class="eyebrow">통신 기록 ${journal.length?journalPage+1:0} / ${journal.length}</div><h2>${a?CHARACTERS[a.who]?.name:'아직 조용한 운전석'}</h2><p class="page-copy">${a?escape(a.text):'요새에 탑승하면 동료들의 이야기가 여기에 남습니다.'}</p><div class="modal-actions"><button id="log-prev" ${journalPage<=0?'disabled':''}>이전</button><button id="log-next" ${journalPage>=journal.length-1?'disabled':''}>다음</button><button id="close-journal" class="primary">전장으로</button></div>`);$('#log-prev').onclick=()=>{journalPage--;drawJournal();};$('#log-next').onclick=()=>{journalPage++;drawJournal();};$('#close-journal').onclick=closeModal;}
function defeat(){save();showModal(`<div class="eyebrow">엔진이 멈췄다. 아직 끝은 아니다.</div><h2>다들 무사해. 다시 맞추자.</h2><p>${state.wave+1}번째 추격에서 엔진이 멈췄습니다. 총 ${state.stats.leaks}명의 적이 방어선을 통과했어요. 출구 사거리와 빠른 적 대응을 다시 살펴보세요.</p><div class="ending-stats"><div><small>달린 시간</small><strong>${fmt(state.time)}</strong></div><div><small>격퇴</small><strong>${state.kills}</strong></div><div><small>조합 발동</small><strong>${state.stats.synergyHits}</strong></div></div><div class="modal-actions"><button id="defeat-menu">메뉴</button><button id="assist">든든한 엔진으로 재시도</button><button id="retry" class="primary">이 구간부터 다시 →</button></div>`);$('#defeat-menu').onclick=()=>{closeModal();home();};const retry=assist=>{state=restoreCheckpoint(state,assist);closeModal();selected=null;ghost=null;paused=false;history=[];gameUI();const line=BARKS.retry[Math.floor(Date.now()/1000)%3];setRadio(...line);save();};$('#retry').onclick=()=>retry(false);$('#assist').onclick=()=>retry(true);}
function ending(){const show=()=>{save();showModal(`<div class="eyebrow">EVERYONE MADE IT HOME</div><h2>고철이 모여, 집이 되었다.</h2><p>국경을 넘었습니다. 리벳은 수리 도구를 내려놓고,<br>보일은 운전석을 떠납니다. 깃이 두 사람의 식사 자리를 맡아 둡니다.</p><div class="ending-stats"><div><small>달린 시간</small><strong>${fmt(state.time)}</strong></div><div><small>격퇴한 추격대</small><strong>${state.kills}</strong></div><div><small>조합 발동</small><strong>${state.stats.synergyHits}</strong></div></div><p>네가 조립한 ${state.towers.filter(t=>t.x!==null).length}개의 기물이 모두를 여기까지 데려왔습니다.</p><div class="modal-actions"><button id="ending-look">우리 요새 바라보기</button><button id="ending-menu" class="primary">제목 화면으로 →</button></div>`);$('#ending-menu').onclick=()=>{closeModal();home();};$('#ending-look').onclick=()=>{closeModal();refresh();setRadio('boil','오늘은 엔진 꺼 둬도 되겠다. 다들 밥 먹으러 갔어. 우리도 가자.');};};if(!state.seen.includes('ending'))showScene('ending',show);else show();}
function events(){let playSound=null;for(const e of state.events){if(e.type==='shot')playSound??=e.weapon;if(e.type==='leak')bark('leak');if(e.type==='rush'){toast('돌격대 접근! 여러 명이 한꺼번에 올라온다.');setRadio('git','뒤쪽 난간에 갈고리가 걸렸어! 여럿이 올라온다. 정비사, 갑판을 부탁해!');$('.radio')?.classList.add('speaking');}}state.events=[];if(playSound)sound(playSound);}
function changedPhase(before){if(state.phase===before)return;selected=null;ghost=null;history=[];refresh();save();if(state.phase==='reward')rewardModal();else if(state.phase==='defeat')defeat();else if(state.phase==='victory')ending();else if(state.phase==='garage'){const scene={1:'firstRush',6:'chapter1',8:'rescue',12:'chapter2',17:'last'}[state.wave];if(scene)showScene(scene);else if(state.towers.filter(t=>t.type==='saw').length>1)bark('saw');else if(sets(state).boiler>=2)bark('fire');else if(state.towers.some(t=>t.x!==null&&modifiers(state,t).links.length))bark('combo');else setRadio('rivet','다음 추격대를 확인해. 무기를 더 얹기 전에, 빈틈부터 보자.');}}
function frame(ts){const dt=Math.min(.1,(ts-last)/1000||0);last=ts;if(screen==='game'&&state){if(!paused&&!modalOpen&&state.phase==='combat'){acc+=dt*speed;let n=0;while(acc>=TICK&&n++<8&&state.phase==='combat'){const before=state.phase;step(state);acc-=TICK;changedPhase(before);}events();}else acc=0;if(ts-lastDraw>=1000/30){renderer?.draw(state,selected,ghost,ts/1000);lastDraw=ts;}uiClock+=dt;if(uiClock>.25){refreshStats();uiClock=0;}}requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state){paused=true;save();refreshStats();}});
window.addEventListener('beforeunload',save);
window.addEventListener('resize',()=>{if(screen==='home')home();else refreshWorkshop();});
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!modalOpen&&screen==='game'){e.preventDefault();togglePause();}if(e.key.toLowerCase()==='r'&&!modalOpen)$('#rotate')?.click();if(e.key==='Escape'&&!modalOpen&&screen==='game'){selected=null;ghost=null;refreshWorkshop();}});
// Read-only snapshots support reproducible diagnostics without changing player state.
window.__rig={snapshot:()=>state?clone(state):null,layout:()=>renderer?.layout?clone(renderer.layout):null};
home();requestAnimationFrame(frame);
