import {W,H,PATH,PATH_KEYS,ITEMS,ENEMIES,TICK,WAVE_COUNT,wavePreview} from './content.js';
export const VERSION=1;
export const clone = x => JSON.parse(JSON.stringify(x));
export function random(s){let x=s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296;}
export function shape(type,rotation=0){let c=ITEMS[type].shape.map(p=>[...p]);for(let i=0;i<(rotation%4+4)%4;i++)c=c.map(([x,y])=>[-y,x]);const mx=Math.min(...c.map(p=>p[0])),my=Math.min(...c.map(p=>p[1]));return c.map(([x,y])=>[x-mx,y-my]);}
export function cells(t){return shape(t.type,t.r).map(([x,y])=>[x+t.x,y+t.y]);}
export function origin(t){const c=cells(t);return {x:c.reduce((a,p)=>a+p[0]+.5,0)/c.length,y:c.reduce((a,p)=>a+p[1]+.5,0)/c.length};}
export function position(p){const n=Math.max(0,Math.min(PATH.length-1.001,p)),i=Math.floor(n),f=n-i,a=PATH[i],b=PATH[Math.min(i+1,PATH.length-1)];return {x:a[0]+.5+(b[0]-a[0])*f,y:a[1]+.5+(b[1]-a[1])*f};}
export function locked(x,y,wave){return wave<8 && ((y===0&&x>=7)||(y===8&&x>=8));}
export function canPlace(s,type,x,y,r=0,ignore=null){const c=shape(type,r).map(([a,b])=>[a+x,b+y]);if(c.some(([a,b])=>a<0||a>=W||b<0||b>=H||PATH_KEYS.has(`${a},${b}`)||locked(a,b,s.wave)))return false;const keys=new Set(c.map(p=>p.join(',')));return !s.towers.some(t=>t.id!==ignore&&t.x!==null&&cells(t).some(p=>keys.has(p.join(','))));}
export function adjacent(a,b){return cells(a).some(([x,y])=>cells(b).some(([u,v])=>Math.abs(x-u)+Math.abs(y-v)===1));}
export function sets(s){const out={iron:new Set(),boiler:new Set(),electric:new Set()};for(const t of s.towers)if(t.x!==null)out[ITEMS[t.type].team].add(t.type);return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,v.size]));}
export function modifiers(s,t){const def=ITEMS[t.type],o=origin(t);let speed=1,damage=1,range=0,chain=0;const links=[];for(const b of s.towers){if(b.id===t.id||b.x===null)continue;const ad=adjacent(t,b);if(ad&&b.type==='feeder'&&['nail','harpoon'].includes(t.type)){speed=Math.min(speed,.72-.08*(b.level-1));links.push(b.id);}if(ad&&b.type==='cooler'&&['mortar','flame'].includes(t.type)){speed=Math.min(speed,.72-.08*(b.level-1));links.push(b.id);}if(ad&&b.type==='battery'&&['coil','winch'].includes(t.type)){damage=Math.max(damage,1.35+.15*(b.level-1));chain=Math.max(chain,.7+.15*(b.level-1));links.push(b.id);}if(b.type==='scope'&&!def.support&&t.type!=='saw'){const bo=origin(b);const aligned=s.towers.filter(a=>a.x!==null&&!ITEMS[a.type].support&&a.type!=='saw').filter(a=>{const ao=origin(a);return Math.abs(ao.x-bo.x)<.6||Math.abs(ao.y-bo.y)<.6;}).sort((a,c)=>distance(origin(a),bo)-distance(origin(c),bo));if(aligned[0]?.id===t.id){range=1.15+.25*(b.level-1);links.push(b.id);}}}return{speed,damage,range,chain,links};}
export function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
export function makeTower(s,type,x=null,y=null,r=0){return{id:s.nextId++,type,x,y,r,level:1,cd:0,age:0,burst:0,aim:0,shots:0,damage:0,kills:0};}
export function createGame(seed=39184){const s={version:VERSION,seed,rng:seed||1,nextId:1,time:0,wave:0,waveTime:0,phase:'garage',hp:100,maxHp:100,kills:0,rewardAt:8,rewards:0,choices:[],rerolls:1,towers:[],enemies:[],shots:[],zones:[],fx:[],events:[],schedule:[],spawnIndex:0,seen:[],log:[],stats:{leaks:0,damage:0,comboDamage:0,synergyHits:0,byType:{},waveResults:[],choices:[]},checkpoint:null};s.towers.push(makeTower(s,'nail',4,2),makeTower(s,'saw',2,5));return s;}
export function emit(s,type,data={}){s.events.push({type,...data});if(s.events.length>30)s.events.shift();}
export function effect(s,type,data){s.fx.push({type,life:.45,maxLife:.45,...data});if(s.fx.length>220)s.fx.shift();}
export function scheduleWave(s){
 const pool=s.wave===0?['grunt']:wavePreview(s.wave).filter(k=>k!=='raider'),out=[],duration=s.wave<3?54:64,count=16+s.wave*4;
 for(let i=0;i<count;i++){let type=pool[i%pool.length];if(type==='boss')type=i===0?'boss':pool[1];let at=2+i*(duration-4)/count;
  if(s.wave<6&&i>=Math.floor(count*.25)&&i<Math.floor(count*.75))at=18+(i-Math.floor(count*.25))*.3;
  out.push({at,type});if(type==='swarm')for(let n=1;n<3;n++)out.push({at:at+n*.18,type});
 }
 if(s.wave===0){for(let n=0;n<4;n++)out.push({at:20+n*.3,type:'runner'});for(let n=0;n<2;n++)out.push({at:18.6+n*.6,type:'armor'});}
 if(s.wave<6)for(let n=0;n<2;n++)out.push({at:19+n*.8,type:'raider'});
 return out.sort((a,b)=>a.at-b.at);
}
export function beginWave(s){if(s.phase!=='garage')return false;if(s.towers.filter(t=>t.x===null).length>1)return false;if(!s.towers.some(t=>t.x!==null&&!ITEMS[t.type].support))return false;if(s.wave%6===0){const snapshot=clone({...s,checkpoint:null,fx:[],events:[]});s.checkpoint=snapshot;}s.phase='combat';s.waveTime=0;s.rushWarned=false;s.schedule=scheduleWave(s);s.spawnIndex=0;s.log.push({type:'startWave',wave:s.wave,time:s.time,hp:s.hp});emit(s,'waveStart');return true;}
export function place(s,id,x,y,r){if(!['garage','reward'].includes(s.phase))return false;const t=s.towers.find(a=>a.id===id);if(!t||!canPlace(s,t.type,x,y,r,id))return false;Object.assign(t,{x,y,r});emit(s,'placed',{id});return true;}
export function stash(s,id){if(!['garage','reward'].includes(s.phase))return false;const t=s.towers.find(a=>a.id===id);if(!t)return false;t.x=null;t.y=null;return true;}
export function discard(s,id){if(!['garage','reward'].includes(s.phase))return false;s.towers=s.towers.filter(t=>t.id!==id);return true;}
export function possiblePlacements(s,type,ignore=null){const a=[];for(let r=0;r<4;r++)for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(canPlace(s,type,x,y,r,ignore))a.push({x,y,r});return a;}
export function chooseOptions(s){
  const pool=Object.keys(ITEMS).filter(k=>ITEMS[k].unlock<=s.wave),out=[];
  if(s.rewards===0)return ['feeder','winch','mortar'];
  const owned=s.towers.filter(t=>t.x!==null).map(t=>t.type),match=pool.filter(k=>owned.includes(k));
  if(match.length)out.push(match[Math.floor(random(s)*match.length)]);
  // One slot follows the workshop the player first chose, without fixing the other slots.
  // Missing types are offered before duplicates, so a build is a decision rather than a lucky recipe.
  const focus=s.focus||'iron',related=pool.filter(k=>ITEMS[k].team===focus&&!out.includes(k));
  const missing=related.filter(k=>!owned.includes(k)),follow=missing.length?missing:related;
  if(follow.length)out.push(follow[Math.floor(random(s)*follow.length)]);
  let n=0;while(out.length<3&&n++<100){const k=pool[Math.floor(random(s)*pool.length)];if(!out.includes(k))out.push(k);}
  // At least one option fits outright, is upgradeable, or is an attacking item that can replace another.
  if(!out.some(k=>s.towers.some(t=>t.type===k&&t.level<3)||possiblePlacements(s,k).length))out[0]='nail';
  return out;
}
export function acceptReward(s,type,mode='new'){if(s.phase!=='reward'||(type!=='repair'&&!s.choices.includes(type)))return null;let result=null;if(type==='repair'){s.hp=Math.min(s.maxHp,s.hp+16);}else if(mode==='upgrade'){const t=s.towers.find(t=>t.type===type&&t.level<3);if(!t)return null;t.level++;result=t;}else{result=makeTower(s,type);s.towers.push(result);}if(!s.focus&&type!=='repair')s.focus=ITEMS[type].team;s.stats.choices.push({wave:s.wave,type,mode});s.rewards++;s.rewardAt=s.kills+Math.round(18+s.rewards*6);s.phase='garage';s.resumeMidWave=true;s.choices=[];emit(s,'rewardChosen');return result;}
export function resume(s){if(s.phase!=='garage'||s.towers.filter(t=>t.x===null).length>1)return false;if(s.resumeMidWave){s.resumeMidWave=false;s.phase='combat';return true;}return beginWave(s);}
export function reroll(s){if(s.phase!=='reward'||s.rerolls<1)return false;s.rerolls--;s.choices=chooseOptions(s);return true;}
function spawn(s,type){const def=ENEMIES[type],scale=1+s.wave*.19+s.wave*s.wave*(type==='boss'?.01:.021);const e={id:s.nextId++,type,p:0,hp:def.hp*scale,maxHp:def.hp*scale,armor:def.armor,speed:def.speed*(1+s.wave*.01),slow:1,hold:0,holdImmune:0,burn:0,burnDps:0,burnOwner:null,lastIron:null,exposed:0,shardCd:0,aura:1,age:0};s.enemies.push(e);}
function hit(s,e,raw,t,kind='normal',chain=false){if(e.hp<=0)return;const ss=s._sets||sets(s),team=t?ITEMS[t.type].team:null;let value=raw,bonus=0;if(team==='iron'&&ss.iron>=2&&e.lastIron&&e.lastIron!==t.type){bonus+=raw*.25;e.exposed=2;}if(team==='iron')e.lastIron=t.type;value+=bonus;if(kind!=='burn'&&kind!=='shock'&&kind!=='pierce')value=Math.max(value*.3,value-e.armor);const real=Math.min(e.hp,value);e.hp-=value;s.stats.damage+=real;if(t){t.damage+=real;s.stats.byType[t.type]=(s.stats.byType[t.type]||0)+real;}if(bonus){s.stats.comboDamage+=Math.min(bonus,real);s.stats.synergyHits++;}if(team==='iron'&&ss.iron>=3&&e.exposed>0&&e.shardCd<=0&&!chain){e.shardCd=1;const p=position(e.p);effect(s,'spark',{...p,color:'#eac16f'});for(const other of s.enemies)if(other.id!==e.id&&other.hp>0&&distance(position(other.p),p)<1.25){hit(s,other,raw*.25,t,'shard',true);s.stats.comboDamage+=raw*.25;}}if(e.hp<=0){s.kills++;if(t)t.kills++;effect(s,'death',{...position(e.p),color:ENEMIES[e.type].color,life:.6,maxLife:.6});emit(s,'kill',{enemy:e.type});}}
function inArc(t,p,range,wide=false){const o=origin(t),dx=p.x-o.x,dy=p.y-o.y,dir=[[1,0],[0,1],[-1,0],[0,-1]][t.r%4],forward=dx*dir[0]+dy*dir[1],side=Math.abs(dx*dir[1]-dy*dir[0]);return forward>=0&&forward<=range&&(wide?side<=forward*.85+.3:side<=.85);}
function attack(s,t,mod,ss){const d=ITEMS[t.type],o=origin(t),range=d.range+(mod.range||0),level=1+(t.level-1)*.7;const viable=s.enemies.filter(e=>e.hp>0&&distance(position(e.p),o)<=range&&distance(position(e.p),o)>=(d.minRange||0)).sort((a,b)=>b.p-a.p);let e=viable[0];if(!e)return false;const power=d.damage*level*mod.damage;t.aim=Math.atan2(position(e.p).y-o.y,position(e.p).x-o.x);
  if(t.type==='nail'){s.shots.push({type:'bullet',x:o.x,y:o.y,target:e.id,speed:12,damage:power,owner:t.id,ttl:2});effect(s,'muzzle',{...o,color:'#fce1a2',life:.12,maxLife:.12});if(t.burst<2){t.burst++;t.cd=.15;}else{t.burst=0;t.cd=d.period*mod.speed;}}
  if(t.type==='saw'){for(const a of viable)hit(s,a,power,t);effect(s,'saw',{...o,color:'#d2b281',life:.16,maxLife:.16});}
  if(t.type==='harpoon'){const targets=s.enemies.filter(a=>a.hp>0&&inArc(t,position(a.p),range)).sort((a,b)=>distance(position(a.p),o)-distance(position(b.p),o));if(!targets.length)return false;for(const a of targets.slice(0,5))hit(s,a,power,t,'pierce');const dir=[[1,0],[0,1],[-1,0],[0,-1]][t.r];effect(s,'beam',{...o,tx:o.x+dir[0]*range,ty:o.y+dir[1]*range,color:'#f2ce85',life:.2,maxLife:.2});}
  if(t.type==='mortar'){e=viable.reduce((best,a)=>{const n=s.enemies.filter(b=>b.hp>0&&distance(position(a.p),position(b.p))<1.35).length;return n>best.n?{e:a,n}:best;},{e,n:0}).e;const p=position(e.p);s.shots.push({type:'shell',...o,sx:o.x,sy:o.y,tx:p.x,ty:p.y,ttl:.9,total:.9,damage:power,owner:t.id,radius:ss.boiler>=3?1.62:1.35,burn:ss.boiler>=3});}
  if(t.type==='flame'){const active=t.age%(2+2*mod.speed)<2;if(!active)return false;const targets=viable.filter(a=>inArc(t,position(a.p),range,true));if(!targets.length)return false;for(const a of targets){hit(s,a,power,t);a.burn=2;a.burnDps=7*level*(ss.boiler>=2?1.4:1);a.burnOwner=t.id;}for(const z of s.zones)if(inArc(t,z,range,true))z.fire=true;effect(s,'flame',{...o,r:t.r,range,color:'#fc9059',life:.22,maxLife:.22});}
  if(t.type==='coil'){let current=e,visited=new Set(),p=o;for(let n=0;n<4+(ss.electric>=2?1:0);n++){if(!current)break;visited.add(current.id);const q=position(current.p);hit(s,current,power*(n? .8:1),t);effect(s,'bolt',{x:p.x,y:p.y,tx:q.x,ty:q.y,color:'#8ef5e0',life:.3,maxLife:.3});p=q;current=s.enemies.filter(a=>a.hp>0&&!visited.has(a.id)&&distance(position(a.p),p)<1.9+mod.chain).sort((a,b)=>distance(position(a.p),p)-distance(position(b.p),p))[0];}}
  if(t.type==='winch'){e=viable.find(a=>a.holdImmune<=0);if(!e)return false;e.hold=e.type==='boss'?.45:e.type==='armor'?.85:1.7;e.holdImmune=4.5;e.holdOwner=t.id;hit(s,e,power,t);effect(s,'tether',{...o,tx:position(e.p).x,ty:position(e.p).y,color:'#a5d5ba',life:e.hold,maxLife:e.hold});}
  if(t.type==='oil'){const p=position(e.p);if(s.zones.length<15)s.zones.push({...p,ttl:6,fire:false,owner:t.id,level});}
  if(mod.links.length||(t.type==='coil'&&ss.electric>=2)||(t.type==='flame'&&ss.boiler>=2))s.stats.synergyHits++;t.shots++;if(t.type!=='nail')t.cd=d.period*mod.speed;emit(s,'shot',{weapon:t.type});return true;
}
export function step(s,dt=TICK){if(s.phase!=='combat')return;s.time+=dt;s.waveTime+=dt;if(s.wave<6&&!s.rushWarned&&s.waveTime>=15){s.rushWarned=true;emit(s,'rush');}s._sets=sets(s);for(const f of s.fx)f.life-=dt;s.fx=s.fx.filter(f=>f.life>0);while(s.spawnIndex<s.schedule.length&&s.schedule[s.spawnIndex].at<=s.waveTime)spawn(s,s.schedule[s.spawnIndex++].type);
  for(const e of s.enemies){if(e.hp<=0)continue;e.age+=dt;e.exposed=Math.max(0,e.exposed-dt);e.shardCd=Math.max(0,e.shardCd-dt);e.holdImmune=Math.max(0,e.holdImmune-dt);const was=e.hold;e.hold=Math.max(0,e.hold-dt);if(was>0&&e.hold===0&&s._sets.electric>=3){const t=s.towers.find(t=>t.id===e.holdOwner),p=position(e.p);effect(s,'blast',{...p,radius:1.3,color:'#8ddaca',life:.5,maxLife:.5});for(const a of s.enemies)if(a.hp>0&&distance(position(a.p),p)<1.3)hit(s,a,20,t,'shock',true);s.stats.comboDamage+=20;}if(e.burn>0){e.burn-=dt;hit(s,e,e.burnDps*dt,s.towers.find(t=>t.id===e.burnOwner),'burn',true);}e.slow=1;for(const z of s.zones)if(distance(position(e.p),z)<1.2){if(z.fire)hit(s,e,12*z.level*dt,s.towers.find(t=>t.id===z.owner),'burn',true);else e.slow=Math.min(e.slow,.55);}if(e.hp<=0)continue;const aura=s.enemies.some(a=>a.type==='captain'&&a.id!==e.id&&a.hp>0&&distance(position(a.p),position(e.p))<2)?1.18:1;e.p+=e.hold>0?0:dt*e.speed*e.slow*aura;if(e.p>=PATH.length-1){s.hp=e.type==='boss'?0:s.hp-ENEMIES[e.type].leak;e.escaped=true;e.hp=0;s.stats.leaks++;emit(s,'leak',{enemy:e.type});effect(s,'leak',{...position(PATH.length-1.01),color:'#f38271',life:.8,maxLife:.8});}}
  for(const z of s.zones)z.ttl-=dt;s.zones=s.zones.filter(z=>z.ttl>0);
  for(const shot of s.shots){shot.ttl-=dt;const owner=s.towers.find(t=>t.id===shot.owner);if(shot.type==='bullet'){const e=s.enemies.find(e=>e.id===shot.target&&e.hp>0);if(!e){shot.ttl=0;continue;}const p=position(e.p),dist=distance(shot,p);if(dist<=shot.speed*dt){hit(s,e,shot.damage,owner);effect(s,'spark',{...p,color:'#eac17e',life:.2,maxLife:.2});shot.ttl=0;}else{shot.x+=(p.x-shot.x)/dist*shot.speed*dt;shot.y+=(p.y-shot.y)/dist*shot.speed*dt;}}else if(shot.ttl<=0){const p={x:shot.tx,y:shot.ty};for(const e of s.enemies)if(e.hp>0&&distance(position(e.p),p)<shot.radius){hit(s,e,shot.damage,owner);if(shot.burn){e.burn=2;e.burnDps=10;e.burnOwner=owner?.id;}}for(const z of s.zones)if(distance(z,p)<shot.radius)z.fire=true;effect(s,'blast',{...p,radius:shot.radius,color:'#eda071',life:.65,maxLife:.65});}}
  s.shots=s.shots.filter(a=>a.ttl>0);s.enemies=s.enemies.filter(e=>e.hp>0);
  for(const t of s.towers){if(t.x===null||ITEMS[t.type].support)continue;t.age+=dt;t.cd-=dt;if(t.cd<=0){if(!attack(s,t,modifiers(s,t),s._sets))t.cd=.1;}}
  s.enemies=s.enemies.filter(e=>e.hp>0);delete s._sets;
  if(s.hp<=0){s.hp=0;s.phase='defeat';emit(s,'defeat');return;}
  if(s.kills>=s.rewardAt&&s.rewards<18&&s.waveTime>8){s.choices=chooseOptions(s);s.phase='reward';emit(s,'reward');return;}
  if(s.spawnIndex>=s.schedule.length&&s.enemies.length===0&&s.waveTime>=60){s.stats.waveResults.push({wave:s.wave,time:s.time,hp:s.hp,kills:s.kills});s.wave++;s.shots=[];s.zones=[];s.fx=[];s.rerolls=s.wave%6===0?1:s.rerolls;if(s.wave>=WAVE_COUNT){s.phase='victory';emit(s,'victory');}else{s.phase='garage';if(s.wave%6===0)s.hp=Math.min(s.maxHp,s.hp+18);emit(s,'waveClear');}}
}
export function restoreCheckpoint(s,assist=false){if(!s.checkpoint)return createGame(s.seed);const c=clone(s.checkpoint);c.checkpoint=clone(s.checkpoint);if(assist){c.maxHp=140;c.hp=140;}c.seen=s.seen;return c;}
export function serialize(s){return JSON.stringify({...s,fx:[],events:[]});}
export function deserialize(raw){const s=JSON.parse(raw);if(s.version!==VERSION||!Array.isArray(s.towers)||!Number.isFinite(s.time)||!Number.isFinite(s.hp)||s.wave<0||s.wave>WAVE_COUNT)throw Error('지원하지 않는 저장 데이터');s.fx=[];s.events=[];return s;}
